// Generated by gencpp from file yolo_ros/TriggerSelectionResponse.msg
// DO NOT EDIT!


#ifndef YOLO_ROS_MESSAGE_TRIGGERSELECTIONRESPONSE_H
#define YOLO_ROS_MESSAGE_TRIGGERSELECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace yolo_ros
{
template <class ContainerAllocator>
struct TriggerSelectionResponse_
{
  typedef TriggerSelectionResponse_<ContainerAllocator> Type;

  TriggerSelectionResponse_()
    : object_names()
    , object_positions()  {
    }
  TriggerSelectionResponse_(const ContainerAllocator& _alloc)
    : object_names(_alloc)
    , object_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _object_names_type;
  _object_names_type object_names;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _object_positions_type;
  _object_positions_type object_positions;





  typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerSelectionResponse_

typedef ::yolo_ros::TriggerSelectionResponse_<std::allocator<void> > TriggerSelectionResponse;

typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionResponse > TriggerSelectionResponsePtr;
typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionResponse const> TriggerSelectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator1> & lhs, const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.object_names == rhs.object_names &&
    lhs.object_positions == rhs.object_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator1> & lhs, const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d609001ca88f5f9d939d2ba261852dbd";
  }

  static const char* value(const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd609001ca88f5f9dULL;
  static const uint64_t static_value2 = 0x939d2ba261852dbdULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_ros/TriggerSelectionResponse";
  }

  static const char* value(const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"string[] object_names\n"
"geometry_msgs/Point[] object_positions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_names);
      stream.next(m.object_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerSelectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_ros::TriggerSelectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "object_names[]" << std::endl;
    for (size_t i = 0; i < v.object_names.size(); ++i)
    {
      s << indent << "  object_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_names[i]);
    }
    s << indent << "object_positions[]" << std::endl;
    for (size_t i = 0; i < v.object_positions.size(); ++i)
    {
      s << indent << "  object_positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.object_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_ROS_MESSAGE_TRIGGERSELECTIONRESPONSE_H
