// Generated by gencpp from file yolo_ros/TriggerSelectionRequest.msg
// DO NOT EDIT!


#ifndef YOLO_ROS_MESSAGE_TRIGGERSELECTIONREQUEST_H
#define YOLO_ROS_MESSAGE_TRIGGERSELECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_ros
{
template <class ContainerAllocator>
struct TriggerSelectionRequest_
{
  typedef TriggerSelectionRequest_<ContainerAllocator> Type;

  TriggerSelectionRequest_()
    {
    }
  TriggerSelectionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerSelectionRequest_

typedef ::yolo_ros::TriggerSelectionRequest_<std::allocator<void> > TriggerSelectionRequest;

typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionRequest > TriggerSelectionRequestPtr;
typedef boost::shared_ptr< ::yolo_ros::TriggerSelectionRequest const> TriggerSelectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace yolo_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_ros/TriggerSelectionRequest";
  }

  static const char* value(const ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request (empty)\n"
;
  }

  static const char* value(const ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerSelectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::yolo_ros::TriggerSelectionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_ROS_MESSAGE_TRIGGERSELECTIONREQUEST_H
