// Generated by gencpp from file yolo_ros/TriggerSelection.msg
// DO NOT EDIT!


#ifndef YOLO_ROS_MESSAGE_TRIGGERSELECTION_H
#define YOLO_ROS_MESSAGE_TRIGGERSELECTION_H

#include <ros/service_traits.h>


#include <yolo_ros/TriggerSelectionRequest.h>
#include <yolo_ros/TriggerSelectionResponse.h>


namespace yolo_ros
{

struct TriggerSelection
{

typedef TriggerSelectionRequest Request;
typedef TriggerSelectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerSelection
} // namespace yolo_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yolo_ros::TriggerSelection > {
  static const char* value()
  {
    return "d609001ca88f5f9d939d2ba261852dbd";
  }

  static const char* value(const ::yolo_ros::TriggerSelection&) { return value(); }
};

template<>
struct DataType< ::yolo_ros::TriggerSelection > {
  static const char* value()
  {
    return "yolo_ros/TriggerSelection";
  }

  static const char* value(const ::yolo_ros::TriggerSelection&) { return value(); }
};


// service_traits::MD5Sum< ::yolo_ros::TriggerSelectionRequest> should match
// service_traits::MD5Sum< ::yolo_ros::TriggerSelection >
template<>
struct MD5Sum< ::yolo_ros::TriggerSelectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yolo_ros::TriggerSelection >::value();
  }
  static const char* value(const ::yolo_ros::TriggerSelectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo_ros::TriggerSelectionRequest> should match
// service_traits::DataType< ::yolo_ros::TriggerSelection >
template<>
struct DataType< ::yolo_ros::TriggerSelectionRequest>
{
  static const char* value()
  {
    return DataType< ::yolo_ros::TriggerSelection >::value();
  }
  static const char* value(const ::yolo_ros::TriggerSelectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yolo_ros::TriggerSelectionResponse> should match
// service_traits::MD5Sum< ::yolo_ros::TriggerSelection >
template<>
struct MD5Sum< ::yolo_ros::TriggerSelectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yolo_ros::TriggerSelection >::value();
  }
  static const char* value(const ::yolo_ros::TriggerSelectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo_ros::TriggerSelectionResponse> should match
// service_traits::DataType< ::yolo_ros::TriggerSelection >
template<>
struct DataType< ::yolo_ros::TriggerSelectionResponse>
{
  static const char* value()
  {
    return DataType< ::yolo_ros::TriggerSelection >::value();
  }
  static const char* value(const ::yolo_ros::TriggerSelectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOLO_ROS_MESSAGE_TRIGGERSELECTION_H
